version: '3'

services:
  latest:
    build: .
    image: jupyter-lab/jl-base
    container_name: "latest"
    environment:
      TZ: Asia/Tokyo
    ports:
      - 8888:8888
    volumes:
      - ./:/home/
    tty: true
